# Generated by Django 5.2 on 2025-04-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0002_add_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excluded',
            field=models.BooleanField(default=False, help_text='Artigos marcados assim não aparecem no menu', verbose_name='Excluído manualmente'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=500, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
