# Generated by Django 5.2 on 2025-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0003_alter_article_excluded_alter_article_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tópico'),
        ),
    ]
