# Generated by Django 5.2 on 2025-04-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0004_alter_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome do cliente'),
        ),
    ]
