# Generated by Django 5.2 on 2025-05-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0006_alter_article_options_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.TextField(unique=True, verbose_name='Link'),
        ),
    ]
