# Generated by Django 5.2 on 2025-05-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsclip', '0007_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram (@...)'),
        ),
        migrations.AddField(
            model_name='client',
            name='x',
            field=models.CharField(blank=True, max_length=100, verbose_name='X/Twitter (@...)'),
        ),
        migrations.AddField(
            model_name='client',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='YouTube (canal/usuário)'),
        ),
    ]
